server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://identity-service:8081
          predicates:
            - Path=/identity/**
        - id: profile-service
          uri: http://profile-service:8082
          predicates:
            - Path=/api/v1/profiles/**,/public/**
        - id: ingestion-service
          uri: http://ingestion-service:8083
          predicates:
            - Path=/api/v1/ingestion/**
        - id: insights-service
          uri: http://insights-service:8084
          predicates:
            - Path=/api/v1/insights/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
