server:
  port: 8084
spring:
  application:
    name: insights-service
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb://localhost:27017/heritagegraph360
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
